name: greenvalue-net
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gitpython
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tensorflow
  - keras-tuner
  - geopandas
  - shapely
  - matplotlib
  - joblib
  - requests
  - pyyaml
  - black